### PR TITLE
Create helm chart

### PR DESCRIPTION
**Pull request by rasheedamir**

### CODE REVIEW

**Comment by stakater-user** [comment]
Tekton - Pipeline ran successfully and image `nexus-docker-openshift-stakater-nexus.apps.binero.06p407u4.kubeapp.cloud/repository/docker/stakater-nordmart-customer:SNAPSHOT-PR-12-e3bc7a72` is available

**Comment by stakater-user** [comment]
Tekton - Pipeline ran successfully and image `nexus-docker-openshift-stakater-nexus.apps.binero.06p407u4.kubeapp.cloud/repository/docker/stakater-nordmart-customer:SNAPSHOT-PR-12-b05b5216` is available

**Comment by stakater-user** [comment]
Tekton - Pipeline ran successfully and image `nexus-docker-openshift-stakater-nexus.apps.binero.06p407u4.kubeapp.cloud/repository/docker/stakater-nordmart-customer:SNAPSHOT-PR-12-f85d3e55` is available

**Review by kahootali — APPROVED** [review]

**Comment by stakater-user** [comment]
Tekton - Pipeline ran successfully and image `nexus-docker-openshift-stakater-nexus.apps.binero.06p407u4.kubeapp.cloud/repository/docker/stakater-nordmart-customer:SNAPSHOT-PR-12-ab62d065` is available

**Pull request merged**
